# Custom extlinux.conf for TemperCrate Development board using FIT image
DEFAULT TemperCrateLinux
TIMEOUT 5

LABEL TemperCrateLinux
    KERNEL /fitImage
    INITRD /st-image-resize-initrd
    APPEND root=PARTUUID=e91c4e10-16e6-4c0e-bd0e-77becf4a3582 rootwait rw console=${console},${baudrate}

