BBPATH .= ":${LAYERDIR}"

BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "tempercrate-bsp"
BBFILE_PATTERN_tempercrate-bsp = "^${LAYERDIR}/"
BBFILE_PRIORITY_tempercrate-bsp = "7"

LAYERSERIES_COMPAT_tempercrate-bsp = "scarthgap"
LAYERDEPENDS_tempercrate-bsp = "core"

# Override ST EULA handling for custom machines
EULA_FILE_ST:stm32mpcommon = "${OPENSTLINUX_BASE}/files/licenses/ST-Proprietary"
EULA_FILE_ST_MD5SUM:stm32mpcommon = "7cb1e55a9556c7dd1a3cae09db9cc85f"