[system]
compatible=temper,stm32mp1
bootloader=uboot
data-directory=/datafs
boot-attempts=1
boot-attempts-primary=1

[keyring]
path=/etc/rauc/ca.cert.pem

[slot.rootfs.0]
device=/dev/mmcblk0p9
type=ext4
bootname=A

[slot.rootfs.1]
device=/dev/mmcblk0p11
type=ext4
bootname=B

[slot.boot.0]
device=/dev/mmcblk0p8
type=ext4
parent=rootfs.0

[slot.boot.1]
device=/dev/mmcblk0p10
type=ext4
parent=rootfs.1

[slot.fip.0]
device=/dev/mmcblk0p5
type=raw
parent=rootfs.0

[slot.fip.1]
device=/dev/mmcblk0p6
type=raw
parent=rootfs.1