# Reuse the vendor (ST) machine settings as baseline.
# Later you can replace this baseline if your production board diverges significantly.
require conf/machine/stm32mp13-disco.conf

# Give the machine its own identity
MACHINE_NAME = "STM32MP13 TemperCrate PROD (initially based on Discovery)"
MACHINEOVERRIDES:append = ":stm32mp13-tempercrate-prod"

# Device Tree to build/deploy for the production board.
KERNEL_DEVICETREE = "st/stm32mp135f-tempercrate-prod.dtb"

# Optional: differentiate artifacts
#IMAGE_BASENAME = "tempercrate-image-core-prod"
