# Custom extlinux.conf for TemperCrate Production Board
DEFAULT TemperCrateLinux
TIMEOUT 0

LABEL TemperCrateLinux
        KERNEL /uImage
        FDT /stm32mp135f-tempercrate-prod.dtb
        INITRD /st-image-resize-initrd
        APPEND root=PARTUUID=e91c4e10-16e6-4c0e-bd0e-77becf4a3582 rootwait rw console=${console},${baudrate}
