# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"
BBPATH:append = ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += " \
  ${LAYERDIR}/recipes-*/*/*.bb \
  ${LAYERDIR}/recipes-*/*/*.bbappend \
  ${LAYERDIR}/recipes-*/*/*/*.bb \
  ${LAYERDIR}/recipes-*/*/*/*.bbappend \
"

BBFILE_COLLECTIONS += "tempercrate"
BBFILE_PATTERN_tempercrate = "^${LAYERDIR}/"
BBFILE_PRIORITY_tempercrate = "6"

LAYERDEPENDS_tempercrate = "core openembedded-layer stm-st-stm32mp st-openstlinux"
LAYERSERIES_COMPAT_tempercrate = "scarthgap"

# Absolute path to the meta-tempercrate repo working tree root
TEMPERCRATE_META_REPO_DIR := "${@os.path.abspath(os.path.join(d.getVar('LAYERDIR'), '..'))}"
